service: proxy-serverless-api
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  # Don't change
  stage: 'prod'
  # Don't change
  region: us-east-1
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  httpApi:
    cors:
      allowedOrigins: 
        - '*'
      allowedHeaders: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      origin: '*'
      headers: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
  restApi:
    cors:
      allowedOrigins: 
        - '*'
      allowedHeaders: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      origin: '*'
      headers: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent

functions:
  getProxy:
    handler: handler.handler
    events:
      - http:
          path: /{name}
          method: get
          cors: true
    tags:
      app: gonzalohirsch.com
